### PR TITLE
Add typings section to package.json

### PR DESCRIPTION
**Pull request by MeirionHughes**
enable support for typings lookup for npm package

### CODE REVIEW

**Comment by samchon** [comment]
When user has header file and installs npm package with ```--save```, then the header file is duplicated and it occurs the duplicated identifier error.

```bash
typings install typescript-stl
npm install --save typescript-stl
```

**Comment by MeirionHughes** [comment]
You don't need to do `typings install typescript-stl` with this PR.

**Comment by samchon** [comment]
Need not to use the typings, it's right if only TypeScript-STL is being used.  However, if there's a library referencing my TypeScript-STL and I enrolled the typescript-stl.d.ts into npm package, then the duplicatation problem must occurs.

Most of TypeScript header files are start with referencing its dependencies. If such dependent relationship exists, then enrolling header file into npm package must cause the critical duplication problem.

```typescript
/// <reference path="../react/react.d.ts" />
/// <reference path="../jquery/jquery.d.ts" />
/// <reference path="../typescript-stl/typescript-stl.d.ts" />
```

**Comment by MeirionHughes** [comment]
That triple comment style is also depreciated. You can remove all `/// <reference path...`  lines, remove `typings/` and do: 

`npm install typescript@2.0.3`
`npm install typescript-stl`
`npm install @types/jquery`
`npm install @types/react`

This is the way typescript has gone... see: https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Comment by samchon** [comment]
Amazing. Thanks for giving me such important news

**Comment by grofit** [comment]
The `reference` style inclusion is no longer used, and was replaced with the more standards compliant ES6 module import/export notion which was added in TS version 1.6 I think. I think most TS libs are moving towards self describing modules as then you dont need to do lots of hoop jumping.

**Comment by samchon** [comment]
PR #2 is merged.

Definition of the latest TypeScript-STL is provided only in TSD yet, but @types also will be provided soon. Thanks for your contribution.

**Comment by samchon** [comment]
Now, using @type is possible.

```npm install --save @types/typescript-stl```

**Pull request merged**
